meta:
  name: 'DKFriends English'
  module: 'DKFriends'
  language:
    name: 'English'
    localizedName: 'English'
    code: 'en'
messages:
  dkfriends.prefix: '&8» &aDKFriends &8|&f'
  dkfriends.prefix.party: '&8» &5DKParty &8|&f'
  dkfriends.prefix.clan: '&8» &3DKClans &8|&f'

  dkfriends.error.onlyPlayer: '{prefix} &cThis command can only be executed as a player'
  dkfriends.error.noPage: '{prefix} &7The page &e{page} &7was not found'
  dkfriends.error.player.notFound: '{prefix} &cThe player &e{name} &cwas not found'
  dkfriends.error.player.notOnline: '{prefix} &cThe player &e{player.displayName} &cis not online'
  dkfriends.error.player.notSelf: '{prefix} &cYou can''t interact with your self'

  dkfriends.error.friend.already: '${dkfriends.prefix} &e{player.displayName} &7is already your friend'
  dkfriends.error.friend.not: '${dkfriends.prefix} &e{player.displayName} &cis not your friend'
  dkfriends.error.friend.empty: '${dkfriends.prefix} &cYou don''t have any friends :('
  dkfriends.error.friend.request.already: '${dkfriends.prefix} &cYou have already sent a friend request to &a{player.displayName}'
  dkfriends.error.friend.request.not: '${dkfriends.prefix} &cYou don''t have a friend request from &a{player.displayName}'
  dkfriends.error.friend.request.empty: '${dkfriends.prefix} &cYou don''t have any friend requests'

  dkfriends.command.friend.add.success: '${dkfriends.prefix} &7You have sent a friend request to &e{player.displayName}'
  dkfriends.command.friend.jump.success: '${dkfriends.prefix} &7Connecting to server..'
  dkfriends.command.friend.list: '${dkfriends.prefix} &7Your friends &8| &7Page&8: &e{page} @for("friend" in {friends},${dkfriends.command.friend.list.loop},"\n","\n")'
  dkfriends.command.friend.list.loop: '@if({friend.online},${dkfriends.command.friend.list.loop.online},${dkfriends.command.friend.list.loop.offline})'
  dkfriends.command.friend.list.loop.online: ' &8- &e{friend.displayName}&8: &aOnline &8(&efriend.server)'
  dkfriends.command.friend.list.loop.offline: ' &8- &e{friend.displayName}&8: &cOffline &8(&7Last seen...&8)'
  dkfriends.command.friend.requests: '${dkfriends.prefix} &7Friend requests &8| &7Page&8: &e{page} @for("request" in {requests},${dkfriends.command.friend.requests.loop},"\n","\n")'
  dkfriends.command.friend.requests.loop: ' &8- &e{request.requester.displayName}&8: !["&8[&aACCEPT&8]"]("run:///friend accept {player.name}") !["&8[&cDENY&8]"]("run:///friend deny {player.name})"'

  dkfriends.friend.request: '${dkfriends.prefix} &e{player.displayName} &7wants to be your friend
  ${dkfriends.prefix} &7Click&8: !["&8[&aACCEPT&8]"]("run:///friend accept {player.name}") !["&8[&cDENY&8]"]("run:///friend deny {player.name})"'
  dkfriends.friend.deny: '${dkfriends.prefix} &e{player.displayName} &chas declined your friend request'
  dkfriends.friend.add: '${dkfriends.prefix} &7You are now friends with &e{player.displayName}'
  dkfriends.friend.remove: '${dkfriends.prefix} &7The friendship with &e{player.displayName} &7was terminated'
  dkfriends.friend.login: '${dkfriends.prefix} &e{player.displayName} &7is now &aonline'
  dkfriends.friend.logout: '${dkfriends.prefix} &e{player.displayName} &7is now &coffline'
  dkfriends.friend.loginInfo.requests: '${dkfriends.prefix} &7You have &e{amount} &7open friend requests'
  dkfriends.friend.loginInfo.one: '${dkfriends.prefix} &7Currently is only &e{player.displayName} &7online'
  dkfriends.friend.loginInfo.two: '${dkfriends.prefix} &7Currently are &e{player.displayName} and &e{player2.displayName} &7online'
  dkfriends.friend.loginInfo.three: '${dkfriends.prefix} &7Currently are &e{player.displayName}, &e{player2.displayName} and &e{player3.displayName} &7online'
  dkfriends.friend.loginInfo.more: '${dkfriends.prefix} &7Currently are &e{player.displayName}, &e{player2.displayName} and &e{otherAmount} &7online'
