meta:
  name: 'DKFriends English'
  module: 'DKFriends'
  language:
    name: 'English'
    localizedName: 'English'
    code: 'en'
messages:
  dkfriends.prefix.friend: '&8» &aDKFriends &8|&f'
  dkfriends.prefix.party: '&8» &5DKParty &8|&f'
  dkfriends.prefix.clan: '&8» &3DKClans &8|&f'

  dkfriends.error.onlyPlayer: '{prefix} &cThis command can only be executed as a player'
  dkfriends.error.noPage: '{prefix} &7The page &e{page} &7was not found'
  dkfriends.error.player.notFound: '{prefix} &cThe player &e{name} &cwas not found'
  dkfriends.error.player.notOnline: '{prefix} &cThe player &e{player.displayName} &cis not online'
  dkfriends.error.player.notSelf: '{prefix} &cYou can''t interact with your self'

  dkfriends.error.friend.already: '${dkfriends.prefix.friend} &e{player.displayName} &7is already your friend'
  dkfriends.error.friend.not: '${dkfriends.prefix.friend} &e{player.displayName} &cis not your friend'
  dkfriends.error.friend.empty: '${dkfriends.prefix.friend} &cYou don''t have any friends :('
  dkfriends.error.friend.request.already: '${dkfriends.prefix.friend} &cYou have already sent a friend request to &a{player.displayName}'
  dkfriends.error.friend.request.not: '${dkfriends.prefix.friend} &cYou don''t have a friend request from &a{player.displayName}'
  dkfriends.error.friend.request.empty: '${dkfriends.prefix.friend} &cYou don''t have any friend requests'

  dkfriends.error.party.not: '${dkfriends.prefix.party} &cYou are not in a party'
  dkfriends.error.party.already: '${dkfriends.prefix.party} &cYou are already in a party'
  dkfriends.error.party.notAllowed: '${dkfriends.prefix.party} &cYou are not allowed to perform this action'
  dkfriends.error.party.notMember: '${dkfriends.prefix.party} &c{player.displayName} &cis not a member of this party'
  dkfriends.error.party.invitation.not: '${dkfriends.prefix.party} &cYou are not invited to this party'

  dkfriends.command.friend.help: '${dkfriends.prefix.friend} &7Available commands
  &7/friend add <player> &8- &7Add a new friend
  &7/friend accept <player> &8- &7Accept a friend request
  &7/friend deny <player> &8- &7Deny a friend request
  &7/friend remove <player> &8- &7Remove a friend
  &7/friend list &8- &7List your friends
  &7/friend requests &8- &7List your friend requests
  &7/friend clear &8- &7Clear all friends
  &7/friend favorite <player> &8- &7Mark a friend as favorite
  &7/friend jump <player> &8- &7Jump to a friend
  &7/friend message <player> <message> &8- &7Send a message
  &7/friend setting <setting> &8- &7Change a setting'
  dkfriends.command.friend.add.success: '${dkfriends.prefix.friend} &7You have sent a friend request to &e{player.displayName}'
  dkfriends.command.friend.jump.success: '${dkfriends.prefix.friend} &7Connecting to server..'
  dkfriends.command.friend.list: '${dkfriends.prefix.friend} &7Your friends &8| &7Page&8: &e{page} @for("friend" in {friends},${dkfriends.command.friend.list.loop},"\n","\n")'
  dkfriends.command.friend.list.loop: '@if({friend.online},${dkfriends.command.friend.list.loop.online},${dkfriends.command.friend.list.loop.offline})'
  dkfriends.command.friend.list.loop.online: ' @if({friend.favorite},"&6✦","&8-") &e{friend.displayName}&8: &aOnline &8(&efriend.server)'
  dkfriends.command.friend.list.loop.offline: ' @if({friend.favorite},"&6✦","&8-") &e{friend.displayName}&8: &cOffline &8(&7Last seen...&8)'
  dkfriends.command.friend.requests: '${dkfriends.prefix.friend} &7Friend requests &8| &7Page&8: &e{page} @for("request" in {requests},${dkfriends.command.friend.requests.loop},"\n","\n")'
  dkfriends.command.friend.requests.loop: ' &8- &e{request.requester.displayName}&8: !["&8[&aACCEPT&8]"]("run:///friend accept {player.name}") !["&8[&cDENY&8]"]("run:///friend deny {player.name})"'
  dkfriends.command.friend.favorite.mark: '${dkfriends.prefix.friend} &7You marked {player.displayName} &7as favorite'
  dkfriends.command.friend.favorite.unmark: '${dkfriends.prefix.friend} &7You unmarked {player.displayName} &7as favorite'

  dkfriends.command.party.help: '${dkfriends.prefix.friend} &7Available commands
  &7/party create &8- &7Create a party
  &7/party delete &8- &7Delete the party
  &7/party invite <player> &8- &7Invite a player
  &7/party accept <player> &8- &7Accept a party invitation
  &7/party deny <player> &8- &7Accept a party invitation
  &7/party leave &8- &7Leave the party
  &7/party kick <player> &8- &7Kick a player from the party
  &7/party jump &8- &7Jump to the party leader
  &7/party message <message> &8- &7Send a message'
  dkfriends.command.party.created: '${dkfriends.prefix.party} &7A new party was created
  ${dkfriends.prefix.party} !["&8[&aInvite your friends&8]"]("run:///friend party") ${dkfriends.prefix.party} !["&e[&aMake public&8]"]("run:///party public")'
  dkfriends.command.party.invited: '${dkfriends.prefix.party} &e{player.displayName} &7was invited to your party'
  dkfriends.command.party.info: '${dkfriends.prefix.party}
  &8»Public: {party.public}
  &8»Category: {party.category}
  &8»Topic: {party.topic}
  &8»Members: &e{party.size} {party.topic} @for("member" in {party.members},${dkfriends.command.party.info.loop},"\n","\n")'
  dkfriends.command.party.info.loop: ' &8- &e{member.displayName} &8(&7{member.role}&8)'

  dkfriends.friend.request: '${dkfriends.prefix.friend} &e{player.displayName} &7wants to be your friend
  ${dkfriends.prefix.friend} &7Click&8: !["&8[&aACCEPT&8]"]("run:///friend accept {player.name}") !["&8[&cDENY&8]"]("run:///friend deny {player.name})"'
  dkfriends.friend.deny: '${dkfriends.prefix.friend} &e{player.displayName} &chas declined your friend request'
  dkfriends.friend.add: '${dkfriends.prefix.friend} &7You are now friends with &e{player.displayName}'
  dkfriends.friend.remove: '${dkfriends.prefix.friend} &7The friendship with &e{player.displayName} &7was terminated'
  dkfriends.friend.login: '${dkfriends.prefix.friend} &e{player.displayName} &7is now &aonline'
  dkfriends.friend.logout: '${dkfriends.prefix.friend} &e{player.displayName} &7is now &coffline'
  dkfriends.friend.loginInfo.requests: '${dkfriends.prefix.friend} &7You have &e{amount} &7open friend requests'
  dkfriends.friend.loginInfo.one: '${dkfriends.prefix.friend} &7Currently is only &e{player.displayName} &7online'
  dkfriends.friend.loginInfo.two: '${dkfriends.prefix.friend} &7Currently are &e{player.displayName} and &e{player2.displayName} &7online'
  dkfriends.friend.loginInfo.three: '${dkfriends.prefix.friend} &7Currently are &e{player.displayName}, &e{player2.displayName} and &e{player3.displayName} &7online'
  dkfriends.friend.loginInfo.more: '${dkfriends.prefix.friend} &7Currently are &e{player.displayName}, &e{player2.displayName} and &e{otherAmount} &7online'

  dkfriends.party.invite: '${dkfriends.prefix.party} &e{invitation.inviter.displayName} &7invited you to a party
  ${dkfriends.prefix.party} &7Click&8: !["&8[&aACCEPT&8]"]("run:///party accept {invitation.partyId}") !["&8[&cDENY&8]"]("run:///party deny {invitation.partyId}")"'
  dkfriends.party.join: '${dkfriends.prefix.party} &e{player.displayName} &7joined the party'
  dkfriends.party.leaved: '${dkfriends.prefix.party} &e{player.displayName} &7left the party'
  dkfriends.party.delete: '${dkfriends.prefix.party} &7The party was deleted'
  dkfriends.party.message: '${dkfriends.prefix.party} &e{player.displayName}&8: &7{message}'
  dkfriends.party.teleport: '${dkfriends.prefix.party} &7Connecting to &e{target.name}'
